# Generated by Django 2.1.7 on 2020-08-06 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='dama',
            new_name='humidity',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='rotobat',
            new_name='temp',
        ),
    ]
