# Generated by Django 2.1.7 on 2020-08-21 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200821_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='create_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='update_date',
            new_name='updated_at',
        ),
    ]
