# Generated by Django 2.1.7 on 2020-08-21 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='API',
        ),
    ]
